# Generated by Django 3.2.9 on 2021-11-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='username',
            field=models.TextField(default=None),
        ),
    ]
